### ISSUE TITLE
Configuration reloading

### ISSUE THREAD

**Issue by virustotalop** [ClubObsidian/DynamicGui#31]
Allow reloading guis.

**Comment by haloflooder** [comment]
How will the plugin handle reloading when it comes to gui's that's currently in use by a player? Will it close any gui the player have open or will the older gui still be active if it's open?

Instead of closing all the gui's instantly when being reloaded. What if there was a command/method to close the gui's optionally via command or config? (e.g. closeGuiOnReload: true or /dyngui forceclose <player/all>)

Oh, and if you plan on closing all the gui's in use. Make sure that it only does that with gui's that's not handled by other plugins if possible.

**Comment by virustotalop** [comment]
How does 248ce6d6fbabe6f18282032c07b124f5c161aff8 look @haloflooder

**Comment by haloflooder** [comment]
@virustotalop Yah gud. But do more guuder plz
